spring.application.name=TO DO
server.port=8089

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/newToDo
spring.datasource.username=postgres
spring.datasource.password=1234
# Hibernate Properties

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api